/*Practice Java programming to compute interest earned by a savings account
 * with a known yearly interest rate.
 * 
 *  input: Amount in US Dollars to save.
 *  Output: Total amount of interest accrued during a period of time. 
 *  
 *  Program by: Ryan Rodriguez and Robert Diaz.
 * 
 *                     July 17th, 2017 
 *
 * ***********************************************************************************/

package interestcalc;


public class Calculator 
{

	private double loanAmount;
	private double interestRate;
	
	
	public static void main(String args[])
	{
		
		
		
		
		
	}
	
	public static void GatherData()
	{
	
		
		
		
	}
	
	private static double ComputedInterest(double P, double T, double R)
	{
		double A = (P * Math.E * Math.pow(R, T) );
		
		double ComputedInterest = (A - P);
		
		
		
		return ComputedInterest;
		
		//This returns the actual amount of ibterest generated by initial savings amount.
	}
	
	
	
	
	
	
	
	}
