/*Practice Java programming to compute interest earned by a savings account
 * with a known yearly interest rate.
 * 
 *  input: Amount in US Dollars to save.
 *  Output: Total amount of interest accrued during a period of time. 
 *  
 *  Program by: Ryan Rodriguez and Robert Diaz.
 * 
 *                     July 17th, 2017 
 *
 * ***********************************************************************************/

package interestcalc;

import java.util.Scanner;

// collaboration project by Ryan Rodriguez and M. Robert Diaz Jr.



public class Calculator 
{

	private static double loanAmount = 100;
	private static double interestRate = 1.1;
	private static double years = 1;

	public static void main(String args[]){
		GatherData();			
		System.out.println("The interest will be $" + ComputedInterest(loanAmount, years, interestRate));
	}

	private static void GatherData(){ // Asks user for info needed and sets it to globals
		Scanner s = new Scanner(System.in);

		System.out.println("What is the amount of your principle? (Loan amount)");
		loanAmount = Double.parseDouble(s.nextLine());

		System.out.println("What is the interest rate? (%)");
		interestRate = Double.parseDouble(s.nextLine()) / 100;

		System.out.println("How long will this interest accumulate? (In days)");
		years = Double.parseDouble(s.nextLine()) / 365;

		System.out.println("Perfect!");
		s.close();
	}
	private static double ComputedInterest(double P, double T, double R)
	{
		double A = (P * Math.pow(Math.E, (R*T)));
		
		double ComputedInterest = (A - P);
		
		return ComputedInterest;

		//This returns the actual amount of interest generated by initial savings amount.
	}



}



